import random

quotes = {
    'motivational': [
        '💪 "Your limitation—it’s only your imagination." - Unknown',
        '🌟 "Push yourself, because no one else is going to do it for you." - Unknown',
        '🔥 "Great things never come from comfort zones." - Unknown',
        '🚀 "Dream it. Wish it. Do it." - Unknown',
        '💪 "Success doesn’t just find you. You have to go out and get it." - Unknown',
        '🌟 "The harder you work for something, the greater you’ll feel when you achieve it." - Unknown',
        '🔥 "Dream bigger. Do bigger." - Unknown',
        '🚀 "Don’t stop when you’re tired. Stop when you’re done." - Unknown',
        '💪 "Wake up with determination. Go to bed with satisfaction." - Unknown',
        '🌟 "Do something today that your future self will thank you for." - Unknown',
        '💪 "The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt',
        '🌟 "It always seems impossible until it’s done." - Nelson Mandela',
        '🔥 "What you get by achieving your goals is not as important as what you become by achieving your goals." - Zig Ziglar',
        '🚀 "The only way to do great work is to love what you do." - Steve Jobs',
        '💪 "Don’t watch the clock; do what it does. Keep going." - Sam Levenson',
        '🌟 "Keep your face always toward the sunshine—and shadows will fall behind you." - Walt Whitman',
        '🔥 "The best way to get started is to quit talking and begin doing." - Walt Disney',
        '🚀 "Hardships often prepare ordinary people for an extraordinary destiny." - C.S. Lewis',
        '💪 "Believe you can and you’re halfway there." - Theodore Roosevelt',
        '🌟 "The only limit to our realization of tomorrow will be our doubts of today." - Franklin D. Roosevelt',
    ],
    'inspirational': [
        '🌈 "The best way to predict the future is to create it." - Peter Drucker',
        '✨ "Believe you can and you’re halfway there." - Theodore Roosevelt',
        '🌟 "Act as if what you do makes a difference. It does." - William James',
        '🔥 "Success is not how high you have climbed, but how you make a positive difference to the world." - Roy T. Bennett',
        '🚀 "Your limitation—it’s only your imagination." - Unknown',
        '💡 "Sometimes later becomes never. Do it now." - Unknown',
        '🌟 "Great things never come from comfort zones." - Unknown',
        '🔥 "Dream it. Wish it. Do it." - Unknown',
        '💪 "Success doesn’t just find you. You have to go out and get it." - Unknown',
        '🌟 "The harder you work for something, the greater you’ll feel when you achieve it." - Unknown',
        '🌈 "Do what you can, with what you have, where you are." - Theodore Roosevelt',
        '✨ "What lies behind us and what lies before us are tiny matters compared to what lies within us." - Ralph Waldo Emerson',
        '🌟 "Happiness is not something ready made. It comes from your own actions." - Dalai Lama',
        '🔥 "In the middle of every difficulty lies opportunity." - Albert Einstein',
        '🚀 "The only way to achieve the impossible is to believe it is possible." - Charles Kingsleigh',
        '💡 "You are never too old to set another goal or to dream a new dream." - C.S. Lewis',
        '🌟 "Everything you’ve ever wanted is on the other side of fear." - George Addair',
        '🔥 "Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill',
        '🚀 "The only limit to our realization of tomorrow will be our doubts of today." - Franklin D. Roosevelt',
        '💡 "The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt',
    ],
    'funny': [
        '😂 "I am not lazy, I am on energy-saving mode." - Unknown',
        '🤣 "Why don’t scientists trust atoms? Because they make up everything!" - Unknown',
        '😜 "I’m on a seafood diet. I see food and I eat it." - Unknown',
        '🤪 "Life is short. Smile while you still have teeth." - Unknown',
        '😂 "I told my computer I needed a break, and now it won’t stop sending me KitKats." - Unknown',
        '🤣 "I’m not arguing, I’m just explaining why I’m right." - Unknown',
        '😜 "I’m not great at advice. Can I interest you in a sarcastic comment?" - Chandler Bing',
        '🤪 "I used to think I was indecisive, but now I’m not so sure." - Unknown',
        '😂 "I’m not lazy, I’m just on my energy-saving mode." - Unknown',
        '🤣 "If at first you don’t succeed, then skydiving definitely isn’t for you." - Unknown',
        '😜 "I’m on a whiskey diet. I’ve lost three days already." - Tommy Cooper',
    ],
    'romantic': [
        '❤️ "You are my sun, my moon, and all my stars." - E.E. Cummings',
        '💖 "I love you not because of who you are, but because of who I am when I am with you." - Roy Croft',
        '💕 "Every love story is beautiful, but ours is my favorite." - Unknown',
        '💘 "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement." - F. Scott Fitzgerald',
        '🌹 "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more." - Angelita Lim',
        '💞 "I would rather spend one lifetime with you than face all the ages of this world alone." - J.R.R. Tolkien',
        '💓 "You don’t love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear." - Oscar Wilde',
        '💌 "If I had a flower for every time I thought of you, I could walk through my garden forever." - Alfred Tennyson',
        '💝 "I am who I am because of you. You are every reason, every hope, and every dream I’ve ever had." - Nicholas Sparks',
        '💗 "To the world, you may be one person, but to one person you are the world." - Dr. Seuss',
        '💖 "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams." - Dr. Seuss',
    ]
}

def get_random_quote(category):
    return random.choice(quotes.get(category, quotes["motivational"]))
